CREATE TABLE dirac.outreach_runs (
    run_id TEXT PRIMARY KEY,
    country TEXT NOT NULL,
    model TEXT,
    run_date TEXT NOT NULL,
    companies_found INTEGER DEFAULT 0,
    contacts_found INTEGER DEFAULT 0
);
CREATE TABLE dirac.outreach_companies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES dirac.outreach_runs(run_id) ON DELETE CASCADE,
    company TEXT NOT NULL,
    website TEXT,
    overview TEXT,
    uae_mohap TEXT,
    uae_upp TEXT,
    mohap_agents TEXT,
    upp_agents TEXT,
    contacts TEXT
);
CREATE INDEX outreach_companies_run_id_idx ON dirac.outreach_companies(run_id, id);
CREATE TABLE dirac.analysis_runs (
    run_id TEXT PRIMARY KEY,
    source_name TEXT NOT NULL,
    source_type TEXT DEFAULT 'upload',
    model TEXT DEFAULT '',
    saved_at TEXT NOT NULL,
    stats TEXT DEFAULT '{}',
    result TEXT DEFAULT '{}',
    report TEXT DEFAULT '',
    has_report INTEGER DEFAULT 0
);
CREATE TABLE dirac.my_portfolio (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    company_name TEXT NOT NULL,
    result TEXT DEFAULT '{}',
    report TEXT DEFAULT '',
    saved_at TEXT NOT NULL
);
CREATE TABLE dirac.pipeline_decisions (
    molecule TEXT PRIMARY KEY,
    decision TEXT NOT NULL CHECK (decision IN ('yes', 'maybe', 'no')),
    source_name TEXT DEFAULT '',
    snapshot TEXT DEFAULT '{}',
    updated_at TEXT NOT NULL
);

-- The API uses a direct PostgreSQL connection. Keep these tables unavailable
-- to Supabase Data API roles even if this schema is exposed later.
ALTER TABLE dirac.outreach_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE dirac.outreach_companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE dirac.analysis_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE dirac.my_portfolio ENABLE ROW LEVEL SECURITY;
ALTER TABLE dirac.pipeline_decisions ENABLE ROW LEVEL SECURITY;
